python test_preprocess.py
python keras_bgru_cv2_generate_fold10.py
python keras_pooled_gru_cnn_cv_fold10.py
python keras_ReLu_cv.py
python keras_Attention_dropout.py
python keras_capsule_fold10.py
python keras_lstm_neptune_generate_cv_fold10.py